default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: airsoft_manager_development

test:
  <<: *default
  database: airsoft_manager_test

production:
  primary: &primary_production
    <<: *default
    database: airsoft_manager_production
    username: airsoft_manager
    password: <%= ENV["AIRSOFT_MANAGER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: airsoft_manager_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: airsoft_manager_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: airsoft_manager_production_cable
    migrations_paths: db/cable_migrate
